In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

INFO:tensorflow:Using local port 16819
INFO:tensorflow:Using local port 19600
INFO:tensorflow:Using local port 20723
INFO:tensorflow:Using local port 23772
INFO:tensorflow:Using local port 21498
INFO:tensorflow:Using local port 18201
INFO:tensorflow:Using local port 21484
INFO:tensorflow:Using local port 22936
INFO:tensorflow:Using local port 16092
INFO:tensorflow:Using local port 24184


In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(len(x))
print(len(y))

10000
10000


In [44]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [45]:
print(y)

[1 0 1 ... 1 1 0]


In [46]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])

In [47]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(x))

In [49]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [50]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

/Users/vishaljha/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/vishaljha/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/vishaljha/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [52]:
ann = tf.keras.models.Sequential()

In [53]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [54]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [55]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [56]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [57]:
ann.fit(x_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5746 - accuracy: 0.7412
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4664 - accuracy: 0.7993
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4416 - accuracy: 0.8101
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4288 - accuracy: 0.8166
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8209
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4121 - accuracy: 0.8236
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4062 - accuracy: 0.8276
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4014 - accuracy: 0.8270
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3971 - accuracy: 0.8273
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3930 - accura

In [58]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [59]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [60]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1516   79]
 [ 201  204]]


0.86